[package]
name = "subgeom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true, features = ["derive", "rc"] }
enum_dispatch = { workspace = true }
array_map = { workspace = true, features = ["derive", "serde", "std"] }
thiserror = { workspace = true }
gds21 = { workspace = true }
