[package]
name = "sublut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = { workspace = true, features = ["clippy"] }
serde = { workspace = true, features = ["derive", "rc"] }
splines = { workspace = true }

[dev-dependencies]
float_eq = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
