[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darling = "0.24.1"
syn = "3.0.6"
quote = "1.0.26"
paste = "1.0.12"
proc-macro2 = "1.0.37"
proc-macro-crate = "3.5.0"
itertools = "0.15.0"

[lib]
proc-macro = true
