[package]
description = "Gds21 Integrated Circuit Layout Parser & Writer"
name = "gds21"
# Shared layout21 attributes
authors = ["Dan Fritchman <dan@fritch.mn>"]
edition = "2018"
license = "BSD-3-Clause"
repository = "https://github.com/dan-fritchman/Layout21"
version = "0.2.1"
workspace = "../../"
exclude = ["resources",]

[dependencies]
byteorder = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
derive_builder = { workspace = true }
derive_more = { workspace = true, features = ["add", "add_assign", "from"] }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_derive = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
toml = { workspace = true }
tempfile = { workspace = true, optional = true }
arcstr = { workspace = true, features = ["serde"] }
textwrap = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[features]
selftest = ["tempfile"]
