[package]
name = "ngspice"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Substrate plugin for Ngspice"

[dependencies]
lazy_static = { workspace = true }
serde = { workspace = true, features = ["derive"] }
substrate = { workspace = true }
tera = { workspace = true, features = ["glob_fs"] }
spice_rawfile = { workspace = true }
anyhow = { workspace = true }
