[package]
name = "substrate"
version = "0.1.0"
edition = "2021"
authors = ["Rahul Kumar <rahulkumar@berkeley.edu>", "Rohan Kumar <rohankumar@berkeley.edu>"]

[dependencies]
derive_builder = { workspace = true, features = ["clippy"] }
serde = { workspace = true, features = ["derive", "rc"] }
slotmap = { workspace = true, features = ["serde"] }
tempfile = { workspace = true }
thiserror = { workspace = true }
enum_dispatch = { workspace = true }
arcstr = { workspace = true, features = ["serde"] }
derivative = { workspace = true }
flexbuffers = { workspace = true }
gds21 = { workspace = true }
subspice = { workspace = true }
subgeom = { workspace = true }
sublut = { workspace = true }
codegen = { workspace = true }
log = { workspace = true }
array_map = { workspace = true, features = ["derive", "serde", "std"] }
toml = { workspace = true }
lazy_static = { workspace = true }
regex = { workspace = true }
grid = { workspace = true }
state = { workspace = true }
pathfinding = { workspace = true }
itertools = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
bitvec = { workspace = true, features = ["serde"] }
csv = { workspace = true }

[dev-dependencies]
sky130_open_pdk = { workspace = true }
ngspice = { workspace = true }
subgates = { workspace = true }
lazy_static = { workspace = true }
float_eq = { workspace = true }
